### PR TITLE
fix: Make leader election select from the whole Committee

### LINKED ISSUE #755: [consensus] Rotate through all the leader roster
The leader selection process is meant to deterministically chose a leader, for example in a round robin way or even pseudorandom keyed by round.
The function is here [1] [2] :
```rust
    /// Returns a leader node in a round-robin fashion.
    pub fn leader(&self, seed: usize) -> PublicKey {
        let mut keys: Vec<_> = self.authorities.keys().cloned().collect();
        keys.sort();
        keys[seed % self.size()].clone()
```

- Problem 1: this does not select on the basis of stake, but only number, which we should change.
- Problem 2: more subtle. The round (seed) we pass in is filtered by a r % 2 != 0 condition. Meaning that I think we will be selecting a subset of only odd or even validators.
[1]: https://github.com/MystenLabs/narwhal/blob/9c1862af04e8c5ecf9c7504900e9d5d00a088859/consensus/src/bullshark.rs#L145-L161
[2]: https://github.com/MystenLabs/narwhal/blob/9c1862af04e8c5ecf9c7504900e9d5d00a088859/consensus/src/tusk.rs#L145-L164

### PR DESCRIPTION
**Pull request by huitseeker**
Fixes #755

### CODE REVIEW

File: config/tests/config_tests.rs [hunk 1]
```diff
@@ -29,6 +29,24 @@ use std::{fs::File, io::Write};
...
 
+#[test]
+fn leader_election_rotates_through_all() {
+    // this committee has equi-sized stakes
+    let committee = test_utils::committee(None);
+    let mut leader_counts = HashMap::new();
+    let mut leader_counts_stepping_by_2 = HashMap::new();
+    for i in 0..100 {
+        let leader = committee.leader(i);
+        let leader_stepping_by_2 = committee.leader(i * 2);
```
Comment (akichidis) [inline config/tests/config_tests.rs:40]: It's not immediately clear to me what we are trying to test by having the `leader_stepping_by_2` here. @huitseeker could you please provide some info?

File: config/tests/config_tests.rs [hunk 2]
```diff
@@ -29,6 +29,24 @@ use std::{fs::File, io::Write};
...
+        *leader_counts.entry(leader).or_insert(0) += 1;
+        *leader_counts_stepping_by_2
+            .entry(leader_stepping_by_2)
+            .or_insert(0) += 1;
+    }
+    assert!(leader_counts.values().all(|v| *v > 1));
```
Comment (akichidis) [inline config/tests/config_tests.rs:46]: Since we are weighting based on stake would it make sense to also check the diff between the number of times the leaders have been elected and ensure they don't diverge much? (since we use normal distribution).

**Review by akichidis — APPROVED** [review]
Great fix @huitseeker , changes make sense to me (from a non-consensus expert point of view compared to the other peer reviewers).

File: config/tests/config_tests.rs (hunk 2 above)
Comment (huitseeker) [reply config/tests/config_tests.rs:48]: It would be an improvement, but I don't see as a main . 
We use a uniform distribution for the `test_utils::committee` function, which means we are doing Bernouilli sampling. 

If we want to be as general as we can, this test should generate a binomial distribution, something we can test [with a goodness-of-fit test adapted for the discrete case](http://www.stat.yale.edu/~jay/EmersonMaterials/DiscreteGOF.pdf). We can also test exact numbers (the test is deterministic), but this may break the second we get out of our current discipline of iterating through seeds in a particular way. A good trade-off would be to use a simple inequality (e.g. Chebysheff).

I'll open an issue & follow-up.

File: config/tests/config_tests.rs (hunk 1 above)
Comment (huitseeker) [reply config/tests/config_tests.rs:42]: I've added a comment: we iterate through even rounds in practice, and so I wanted to make sure we hit the whole roster (each available validator) reliably.

File: config/src/lib.rs [hunk 3]
```diff
@@ -377,11 +378,21 @@ impl Committee {
...
     }
 
-    /// Returns a leader node in a round-robin fashion.
+    /// Returns a leader node as a weighted choice seeded by the provided integer
     pub fn leader(&self, seed: usize) -> PublicKey {
-        let mut keys: Vec<_> = self.authorities.keys().cloned().collect();
-        keys.sort();
-        keys[seed % self.size()].clone()
+        let mut seed_bytes = [0u8; 32];
+        seed_bytes[32 - 8..].copy_from_slice(&seed.to_le_bytes());
```
Comment (asonnino) [inline config/src/lib.rs:384]: why `32-8`?

**Review by asonnino — APPROVED** [review]

File: config/src/lib.rs (hunk 3 above)
Comment (huitseeker) [reply config/src/lib.rs:384]: The seed is a u64 (8 bytes)
Ah, yes, you're right.We should include the epoch in there.

Comment (asonnino) [reply config/src/lib.rs:384]: got it

File: config/tests/config_tests.rs (hunk 2 above)
Comment (akichidis) [reply config/tests/config_tests.rs]: Thanks for the detailed reply on this! Great to see that you did with solution (2). Definitely (3) is something we could apply here - and now that I can think off we could use in other places in the end to end tests .
