### PR TITLE
Proptest fixes

### LINKED ISSUE #375: Node dag test failure
### Description
The test `test_dag_sanity_check` fails but it is unclear why.

### Steps to reproduce
Remove the `#[ignore]` tag in `node_dag.rs` and run `cargo nextest run |& tee test.out`.

### PR DESCRIPTION
**Pull request by huitseeker**
This is a follow-up to #381, and fixes #375

### CODE REVIEW

File: dag/src/node_dag.rs [hunk 1]
```diff
@@ -385,11 +385,14 @@ mod tests {
         }
 
         #[test]
-        #[ignore = "Issue #375"]
         fn test_dag_sanity_check(
             dag in arb_dag_complete(10, 10)
         ) {
-            assert!(dag.len() <= 100);
+            // the `prop_recursive` combinator used in `arb_dag_complete` is actually probabilistic, see:
+            // https://github.com/AltSysrq/proptest/blob/master/proptest/src/strategy/recursive.rs#L83-L110
```
Comment (asonnino) [inline dag/src/node_dag.rs:392]: Ha!

**Review by asonnino — APPROVED** [review]
